#!/usr/bin/env sh

source "$HOME/.config/sketchybar/color.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/controller"
PLUGIN_TOUCH="$HOME/.config/sketchybar/controller/touch"
ITEM_DIR="$HOME/.config/sketchybar/view"

PADDING=4
ICON="SF Symbols"
LABEL="Iosevka Term"

sketchybar --bar     height=32                                            \
                     blur_radius=0                                        \
                     padding_left=0                                       \
                     padding_right=10                                     \
                     color=0xff${COL_GRAY1:1}                             \
                     position=top                                         \
                     sticky=on                                            \
                     font_smoothing=on                                    \
                                                                          \
           --default updates=when_shown                                   \
                     drawing=on                                           \
                     icon.font="$ICON:SemiBold:13.0"                      \
                     label.font="$LABEL:SemiBold:16.0"                    \
                     icon.padding_left=$PADDING                           \
                     icon.padding_right=$PADDING                          \
                     label.padding_left=$PADDING                          \
                     label.padding_right=$PADDING                         \
                     label.color=0xff${WHITE:1}                           \
                     icon.color=0xff${WHITE:1}                            \


# left
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

# right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/cal.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"

# initializing
sketchybar --update

echo "sketchybar configuration loaded.."
